name:
channels:
- defaults
- conda-forge
dependencies:
- python>=3.9
- pip>=21.3.1
- conda>=4.11.0
- pip:
    - psutil>=5.8.0
    - numpy>=1.21.5
    - matplotlib>=3.5.1
    - joblib>=1.1.0
    - gym>=0.22.0
    - torch>=1.10.1
    - IPython>=8.0.1
